feat: add cards with links (see img)
odysen/infra_website pull request #26
Opened 2024-08-12 10:57 UTC by LucasoDevDotTk

![image](https://github.com/user-attachments/assets/3dab0810-dfb2-41a0-9d4f-10181bed0315)

Yup, so I added this. Content can of course be altered later as needed.

2024-08-12 12:48 UTC, kerichdev commented
looks good to me, but you might wanna take a look at some of the files that you're shipping - some of them probably shouldnt be in the commit since they reference local configs and files on your pc.

secondly, have you tested this on mobile? i'm not sure how the cards will look there

lastly, we should prooooobably rework the logos in the cards to some unique style - because rn it IS a helluvaos rip-off :sob:

2024-08-12 12:49 UTC, kerichdev approved these changes
these look good to me

2024-08-12 12:51 UTC, kerichdev requested changes
look at the comments for the other stuff

2024-08-12 12:51 UTC, kerichdev commented on src/assets/PR.svg
the logo needs to be redesigned to be less of a helluvaos ripoff

2024-08-12 12:51 UTC, kerichdev commented on src/assets/patreonLogo.png
do we need the white background with it?

2024-08-12 12:51 UTC, kerichdev commented on src/components/blogCard.vue
comment for all the cards - we can make them ONE component, and give them arguments for the images, text, and headers - if they share similar layout - that'll save us time down the line

2024-08-12 12:51 UTC, kerichdev commented on src/components/pageHome.vue
does the layout work on mobile?

2024-08-12 12:51 UTC, kerichdev commented on vite.config.js.timestamp-1723377770687-598bad10001d5.mjs
this probably shouldnt be here...

2024-08-12 12:52 UTC, LucasoDevDotTk commented
> looks good to me, but you might wanna take a look at some of the files that you're shipping - some of them probably shouldnt be in the commit since they reference local configs and files on your pc.
> 
> 
> 
> secondly, have you tested this on mobile? i'm not sure how the cards will look there
> 
> 
> 
> lastly, we should prooooobably rework the logos in the cards to some unique style - because rn it IS a helluvaos rip-off :sob: 

I completely forgot about mobile, my fault lol. I'll try to get it to work tmr. As for the the config files, I'll fix that too

2024-08-12 12:55 UTC, kerichdev commented
> > looks good to me, but you might wanna take a look at some of the files that you're shipping - some of them probably shouldnt be in the commit since they reference local configs and files on your pc.
> > secondly, have you tested this on mobile? i'm not sure how the cards will look there
> > lastly, we should prooooobably rework the logos in the cards to some unique style - because rn it IS a helluvaos rip-off 😭
> 
> I completely forgot about mobile, my fault lol. I'll try to get it to work tmr. As for the the config files, I'll fix that too

no problem, take the tiem you need, req a review again after you push all the changes you need

2024-09-05 14:36 UTC, kerichdev approved these changes

2024-09-05 14:37 UTC, kerichdev commented
merging as its been over 3 weeks now - propose further fixes alongside the primary development line :3

2024-09-05 14:37 UTC, merged